# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.CharField(max_length=5000),
        ),
    ]
