# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170622_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='destacada',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
